### ISSUE TITLE
[OpenConv] Your Questions Here

### ISSUE THREAD

**Issue by steinitz** [x43x61x69/Issues#1]
App Version: 1.2
OS X Version: 10.10.2

---

 What can you do to help you? Please write down below:

It uploads to dropbox but doesn't put the shortened url into the pasteboard.  Also no notification.

Seeing this in logs:

20/04/15 11:43:39.989 pm com.apple.xpc.launchd[1]: (ng.reversi.OneShotAgent[7960]) Service exited with abnormal code: 1
20/04/15 11:43:39.989 pm com.apple.xpc.launchd[1]: (ng.reversi.OneShotAgent) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.

**Comment by x43x61x69** [comment]
Hi @steinitz !

At this moment, Google has blocked the shortening service to any Dropbox URLs.

Try selecting other method in the preferences (e.g. Dropbox short Link) and it will work.

Best,
Cai
