### ISSUE TITLE
[Uplr] custom domain or bit.ly support?

### ISSUE THREAD

**Issue by pinchies** [x43x61x69/Issues#4]
App Version: 2.0
OS X Version: 10.10.5

---
Hello Zhi-Wei! 
Any chance of custom domain support (e.g. YOURLS plugin/api support)?

Otherwise could we have bit.ly integration, since bit.ly supports custom domains for free? Bit.ly would also allow stats tracking of shared links.

I'm not a customer yet, I'm looking at buying. I use cloudapp, and their monthly fees are way too high. So I'm looking for a replacement. I like the idea of using dropbox for the file hosting.

:-)

Thanks,
Sam

**Comment by x43x61x69** [comment]
Hi @pinchies ,

Bit.ly support will be rollout in v2.1.0, roughly be out in a about week.

Best,
Cai
